[shell]
clipboard_enabled = false
font_family = "MonaspiceAr Nerd Font Propo"
screen_time_enabled = true

[shell.animation]
speed = 2.0

[theme]
source = "custom"
custom_palette = "dracula"

[audio]
enable_overdrive = true

[control_center]
sidebar = "full"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "mic_mute"

[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]

[idle.behavior.lock]
enabled = true
timeout = 600

[idle.behavior.lock-and-suspend]
timeout = 900

[idle.behavior.screen-off]
enabled = true
timeout = 660

[location]
auto_locate = true

[nightlight]
enabled = true
temperature_night = 3500

[osd]
position = "bottom_center"

[osd.kinds]
media = false

[shell.mpris]
blacklist = ["chromium", "firefox", "mpv"]

[shell.panel]
open_near_click_control_center = true
session_placement = "floating"
session_position = "center"

[shell.screenshot]
pipe_to_command = true
save_to_file = false

[shell.session]
grid = true
grid_columns = 2

[[shell.session.actions]]
action = "lock"
countdown_seconds = 0.0
enabled = true
shortcut = "l"
variant = "outline"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 10.0
enabled = true
shortcut = "e"
variant = "destructive"

[[shell.session.actions]]
action = "lock_and_suspend"
countdown_seconds = 3.0
enabled = true
shortcut = "s"
variant = "secondary"

[[shell.session.actions]]
action = "command"
command = "systemctl hibernate"
countdown_seconds = 10.0
enabled = true
glyph = "zzz"
label = "Hibernate"
shortcut = "h"
variant = "destructive"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 10.0
enabled = true
shortcut = "r"
variant = "destructive"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 10.0
enabled = true
shortcut = "0"
variant = "destructive"

[shell.shadow]
direction = "center"

[wallpaper]
transition = ["fade"]
transition_duration = 500
