# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e673e84a-d7aa-4b85-a53c-009f8e8e6c28";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e673e84a-d7aa-4b85-a53c-009f8e8e6c28".device = "/dev/disk/by-uuid/e673e84a-d7aa-4b85-a53c-009f8e8e6c28";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6993-A392";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d9b5ecb7-4e23-413d-9ba3-0ea4dbeaf1e0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
