[host]
kernel = "cachyos-latest"
users = ["borhane"]
defaultUser = "borhane"
system = "x86_64-linux"

[hardware]
bluetooth = false
wifi = false
touchpad = false
backlight = false
fingerprint = false

[features]
autoUpdate = false
autoReboot = false
zramSwap = false
zSwap = false
remoteUnlock = false
qbittorrent-nox = false
kanata = false

[features.kernel]
cpu = "x86_64-v3"
scheduler = "bore"
lto = "thin"

[features.wol]
enable = false
iface = ""

[features.desktop]
zSwap = true
kanata = true

[hardware.laptop]
bluetooth = true
wifi = true
touchpad = true
backlight = true

[features.laptop]
zramSwap = true
kanata = true

[power]
tlp = true
startChargeThreshold = 65
stopChargeThreshold = 85

[networking]
allowTCP = []
allowUDP = []
