auto-upgrade = false
autoReboot = false
zram-swap = true
zswap = false
remote-unlock = false
kanata = false
gaming = false
allowTCP = []
allowUDP = []
libvirtd = false
virtualbox = false
podman = true
jellyfin = false
adguard = true
openssh = true

[kernel]
opti = "x86_64-v3"
sched = "bore"
lto = "thin"

[wol]
enable = false
iface = ""

[desktop]
kanata = true
libvirtd = true

[laptop]
kanata = true
