[defaults]
kernel = "cachyos-latest"
defaultUser = "borhane"
system = "x86_64-linux"
additionalKernels = []
modules = ["openssh", "fstrim", "fwupd"]

[defaults.users.borhane]

[kamui]
type = "laptop"
description = "P14s G5 AMD"
kernel = "cachyos-latest"
additionalKernels = ["cachyos-lts"]

[kamui.features.kernel]
opti = "zen4"

[kamui.hardware]
disk = "/dev/nvme0n1"
ram = 32
cpu = "amd"
gpu = "amd"
module = "lenovo-thinkpad-p14s-amd-gen5"
fingerprint = true

[kotoamatsukami]
hostname = "koto"
type = "desktop"
description = "5950X Workstation"
kernel = "cachyos-latest"
additionalKernels = ["cachyos-lts"]

[kotoamatsukami.features]
autoUpdate = false
remoteUnlock = true
qbittorrent-nox = true
netbirdPort = 51281
allowTCP = [8096]
gaming = true

[kotoamatsukami.features.kernel]
opti = "x86_64-v3"

[kotoamatsukami.features.wol]
enable = true
iface = "enp6s0"

[kotoamatsukami.hardware]
disk = "/dev/nvme0n1"
ram = 64
cpu = "amd"
gpu = "nvidia"
bluetooth = true
wifi = true

[kotoamatsukami.hardware.disks]
34B1213A561574D4 = "/mnt/2_5"
75cddeb8-910a-41da-8b8c-269dada60016 = "/mnt/3_5"
4d80e49e-7786-4543-aa34-7429908d3c8b = "/mnt/320"
afe8ba39-fada-43da-ba0a-459498b1b062 = "/run/media/borhane/LACIE"
4A9DD7D4448B0F0A = "/run/media/borhane/DATA"

[kotoamatsukami.users.borhane]
email = "guemidiborhane@aina.dz"
