[defaults]
modules = ["nur", "home-config", "pkgs", "dotfiles", "shell", "host-profile"]

[borhane]
id = 1000
name = "Borhaneddine GUEMIDI"
email = "guemidiborhane@gmail.com"
shell = "fish"
authorizedKeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBf7j2Y+EiXT2hmQGljnfUIWLeOOiZ9INuyQWZHwuenN personal@vault",
]
signingKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhxTeNtI20T8uDHETzBIBcDNcM0UbW6pamh3z6zJSIG signing@vault"
extraGroups = ["uinput", "libvirtd"]
