{ _, ... }:
{
  flake.modules.homeManager.hypres =
    {
      config,
      lib,
      pkgs,
      ...
    }:

    let
      cfg = config.programs.hypres;

      python = pkgs.python3.withPackages (
        ps: lib.optionals (lib.versionOlder pkgs.python3.version "3.11") [ ps.tomli ]
      );

      hypres-bin = pkgs.writeScriptBin "hypres" ''
        #!${python}/bin/python3
        ${builtins.readFile ./scripts/hypres.py}
      '';

      commandsToml =
        let
          commandEntries = lib.mapAttrsToList (
            class: cmd: "\"${lib.escape [ "\"" "\\" ] class}\" = \"${lib.escape [ "\"" "\\" ] cmd}\""
          ) cfg.commands;

          # toString on a Nix float gives "4" not "4.0"
          settleEntries = lib.mapAttrsToList (
            class: secs: "\"${lib.escape [ "\"" "\\" ] class}\" = ${toString secs}"
          ) cfg.settle;
        in
        pkgs.writeText "hypres-commands.toml" (
          ''
            # Generated by home-manager — edit via programs.hypres.{commands,settle}
            [commands]
            ${lib.concatStringsSep "\n" commandEntries}
          ''
          + lib.optionalString (cfg.settle != { }) ''

            [settle]
            ${lib.concatStringsSep "\n" settleEntries}
          ''
        );

      # Env vars consumed by the Python script's tunable block.
      # Passed explicitly to every service so the values declared in Nix
      # are the single source of truth.
      serviceEnv = [
        "HYPRES_WINDOW_TIMEOUT=${toString cfg.windowTimeout}"
        "HYPRES_INTER_LAUNCH_GAP=${cfg.interLaunchGap}"
      ];

    in
    {
      options.programs.hypres = {
        enabled = lib.mkEnableOption "hypres Hyprland session restore";

        saveOnSleep = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Save session before suspend/hibernate. Hooks into sleep.target.
          '';
        };

        saveOnLogout = lib.mkOption {
          type = lib.types.bool;
          default = true;
          description = ''
            Save session on logout or system shutdown. Hooks into
            graphical-session.target via ExecStop so it fires on both
            a clean Hyprland exit and a system shutdown.
          '';
        };

        commands = lib.mkOption {
          type = lib.types.attrsOf lib.types.str;
          default = { };
          example = lib.literalExpression ''
            {
              "foot"     = "footclient -D {cwd}";
              "firefox"  = "firefox";
              "vesktop"  = "vesktop";
              "obsidian" = "obsidian";
            }
          '';
          description = ''
            Mapping of Hyprland window class → shell command to launch that app.
            Find a window's class with: hyprctl activewindow -j | jq .class
            Run 'hypres info' after a save to see which classes need entries.
            Use {cwd} in the command to restore the working directory (terminals).
          '';
        };

        settle = lib.mkOption {
          type = lib.types.attrsOf lib.types.number;
          default = { };
          example = lib.literalExpression ''
            {
              "vesktop" = 4;
              "discord" = 4;
            }
          '';
          description = ''
            Per-class splash-screen settle time in seconds. After the first
            openwindow event for a class, hypres collects all windows of that
            class that appear within this window, then picks the one with the
            largest pixel area as the real window. Use for Electron apps
            (Discord, Vesktop, etc.) that open a loading window before the
            main one — without this they get the wrong window claimed and
            end up misplaced or unrestored.
          '';
        };

        windowTimeout = lib.mkOption {
          type = lib.types.int;
          default = 12;
          description = "Seconds to wait for each window to appear during restore.";
        };

        interLaunchGap = lib.mkOption {
          type = lib.types.str;
          default = "0.4";
          description = "Seconds between launching successive apps during restore.";
        };
      };

      config = lib.mkIf cfg.enabled {

        xdg.configFile."hypres/commands.toml".source = commandsToml;

        home.packages = [ hypres-bin ];

        systemd.user.services = lib.mkMerge [

          (lib.mkIf cfg.saveOnSleep {
            hypres-presleep = {
              Unit = {
                Description = "Save Hyprland session before sleep";
                Before = [ "sleep.target" ];
                StopWhenUnneeded = true;
                ConditionEnvironment = "HYPRLAND_INSTANCE_SIGNATURE";
              };
              Service = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStart = "${hypres-bin}/bin/hypres save";
                TimeoutStartSec = "10";
                Environment = serviceEnv;
              };
              Install.WantedBy = [ "sleep.target" ];
            };
          })

          (lib.mkIf cfg.saveOnLogout {
            hypres-logout = {
              Unit = {
                Description = "Save Hyprland session on logout or shutdown";
                After = [ config.wayland.systemd.target ];
                PartOf = [ config.wayland.systemd.target ];
                ConditionEnvironment = "HYPRLAND_INSTANCE_SIGNATURE";
              };
              Service = {
                Type = "oneshot";
                RemainAfterExit = true;
                ExecStart = "${pkgs.coreutils}/bin/true";
                ExecStop = "${hypres-bin}/bin/hypres save";
                TimeoutStopSec = "10";
                Environment = serviceEnv;
              };
              Install.WantedBy = [ config.wayland.systemd.target ];
            };
          })
        ];
      };
    };
}
