#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
startup_command = "ls"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "system"
disable_startup_command = true
windows = ["dotfiles", "nixos"]

[[window]]
name = "dotfiles"
startup_script = "exec yadm enter $EDITOR"

[[window]]
name = "nixos"
path = "~/.config/nixos/"
startup_script = "exec $EDITOR"
