#!/bin/sh

PACKAGES_DIR="$HOME/.config/yadm/packages.d"
TEMP_DIR=$(mktemp --directory)
sh -c "pacman -Qqem >$TEMP_DIR/aur.list" &
sh -c "pacman -Qnqe >$TEMP_DIR/pacman.list" &

wait

LISTS="$TEMP_DIR/*.list"
for list_file in $LISTS; do
  filename=$(basename "$list_file")
  grep -vFxf "$PACKAGES_DIR/local.list" "$list_file" | sort >"$PACKAGES_DIR/$filename"
done

yadm add "$PACKAGES_DIR/pacman.list" "$PACKAGES_DIR/aur.list"
