[borhane]
id = 1000
fullName = "Borhaneddine GUEMIDI"
email = "guemidiborhane@gmail.com"
shell = "fish"
sshKeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBf7j2Y+EiXT2hmQGljnfUIWLeOOiZ9INuyQWZHwuenN personal",
]
yadmRepo = "https://github.com/guemidiborhane/dotfiles.git"
extraGroups = ["uinput", "libvirtd"]
