# vim: ft=hyprlang

source = ~/.config/hypr/colors/dracula.conf

$gnome_schema = gsettings set org.gnome.desktop.interface
exec-once = $gnome_schema gtk-theme 'Dracula'
exec-once = $gnome_schema icon-theme 'kora'
exec-once = $gnome_schema font-name 'Cantarell 11'
exec-once = $gnome_schema monospace-font-name 'MonaspiceAr Nerd Font Propo 11'
exec-once = $gnome_schema color-scheme 'prefer-dark'
exec-once = $gnome_schema accent-color $accent
exec-once = $gnome_schema cursor-theme $XCURSOR_THEME
exec-once = $gnome_schema cursor-size $XCURSOR_SIZE
exec-once = hyprctl setcursor $XCURSOR_THEME $XCURSOR_SIZE

$border_size = 2
$active_border = $purple
$inactive_border = $selection
$nogroup_border = $background

general {
    gaps_in = 5
    gaps_out = 10
    gaps_workspaces = 0

    border_size = $border_size

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $active_border
    col.inactive_border = $inactive_border
    col.nogroup_border = $nogroup_border
    col.nogroup_border_active = $active_border

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 5

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 0.95

    dim_inactive = true
    dim_strength = 0.1

    shadow {
        enabled = true
        color = rgba(1E202966)
        render_power = 3
        range = 60
        offset = 1 2
        scale = 0.97
    }


    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 8
        passes = 3
        ignore_opacity = false
        brightness = 1.0
        xray = false
        vibrancy = 0.3
        vibrancy_darkness = 0.05
        contrast = 1.0
        popups = true
        new_optimizations = true
        noise = 0
    }
}

animations {
    enabled = true

    bezier = instantDecel, 0.2, 0.9, 0.3, 1
    bezier = quickIn, 0.4, 0, 0.8, 0.2
    bezier = balanced, 0.6, 0, 0.2, 1

    animation = windows, 1, 1.05, instantDecel, popin 96%
    animation = windowsOut, 1, 1.0, quickIn, popin 96%

    animation = border, 1, 1.1, instantDecel
    animation = fade, 1, 1.05, instantDecel

    animation = workspaces, 1, 1.35, balanced, slide
    animation = specialWorkspace, 1, 1.25, instantDecel, slidevert
}

group {
    col.border_active = $active_border
    col.border_inactive = $inactive_border

    groupbar {
        enabled = true
        render_titles = yes
        height = 20
        gradients = true
        font_size = 14
        text_color = rgb(ffffff)
        gaps_in = 0
        indicator_height = 0
        gaps_out = -5
        gradient_rounding = 5
        keep_upper_gap = false

        col.active = $active_border
        col.inactive = $inactive_border
    }
}
