# vim: ft=hyprlang

$sw_scratch = workshop
$sw_messaging = messaging
$sw_music = music

workspace = special:$sw_scratch, on-created-empty:$run -- $terminal --app-id workshop-session -e $SHELL -c "wn"
bind = $mod, g, togglespecialworkspace, $sw_scratch
bind = $mod $shift, g, movetoworkspace, special:$sw_scratch
gesture = 3, up, special, $sw_scratch

workspace = special:$sw_music, on-created-empty:$run -- spotify
bind = $mod, s, togglespecialworkspace, $sw_music
bind = $mod $shift, s, movetoworkspace, special:$sw_music

bind = $mod, d, togglespecialworkspace, $sw_messaging
bind = $mod $shift, d, movetoworkspace, special:$sw_messaging


workspace = s[true], layout:scrolling

windowrule {
  name = messaging-to-special
  workspace = special:$sw_messaging silent
  match:class = ^(org.telegram.desktop|signal|vesktop|thunderbird)$
}

windowrule {
  name = music-to-special
  workspace = special:$sw_music silent
  match:class = ^(spotify)$
}

