# vim: ft=hyprlang

workspace = special:$scratch, on-created-empty:$run -- $terminal -e $SHELL -c "wn"
workspace = 1, on-created-empty:$run -- xdg-open https://
workspace = special:$scratch, layout:scrolling

source = ~/.config/hypr/conf.d/workspace_monitor.conf
