# vim: ft=hyprlang

$ipc = noctalia-shell ipc call

bind = $alt, Z, exec, $ipc notifications toggleHistory
bind = $mod, 0, exec, $ipc sessionMenu toggle

bindel = ,XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = ,XF86MonBrightnessDown, exec, $ipc brightness decrease

bindel = ,XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = ,XF86AudioLowerVolume, exec, $ipc volume decrease
bindel = ,XF86AudioMute, exec, $ipc volume muteOutput
bindel = ,XF86AudioMicMute, exec, $ipc volume muteInput

bindl = , XF86AudioNext, exec, $ipc media next
bindl = $shift, XF86AudioNext, exec, $ipc media previous
bindl = , XF86AudioPrev, exec, $ipc media previous
bindl = , XF86AudioPause, exec, $ipc media playPause
bindl = , XF86AudioPlay, exec, $ipc media playPause

bindr = $meta $ctrl, W, workspace, emptym
bindr = $meta $ctrl, W, exec, $ipc wallpaper toggle

$pause_media = $ipc media pause
$lock_session = $ipc lockScreen lock
$screen_off = sleep 0.5 && hyprctl dispatch dpms off
bindr = $alt $shift, L, exec, $pause_media & $lock_session && $screen_off

