#!/bin/sh
# ~/.config/hypr/hyprexit

# with openrc use loginctl
[ "$(cat /proc/1/comm)" = "systemd" ] && logind=systemctl || logind=loginctl

case "$1" in
lock)
    hyprlock
    ;;
logout)
    ~/.config/hypr/helpers/exit.sh
    ;;
suspend)
    $logind suspend
    ;;
hibernate)
    $logind hibernate
    ;;
reboot)
    $logind reboot
    ;;
shutdown)
    $logind poweroff
    ;;
*)
    echo "== ! hyprexit: missing or invalid argument ! =="
    echo "Try again with: lock | logout | suspend | hibernate | reboot | shutdown"
    exit 2
    ;;
esac

exit 0
