#!/bin/sh

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

log "Starting Hyprland session wrapper"

# Source profile files
source_profiles() {
  for profile in /etc/profile /usr/local/etc/profile "$HOME/.profile"; do
    [ -f "$profile" ] && . "$profile"
  done
}

# Shell-specific initialization
initialize_shell() {
  case $SHELL in
  */bash)
    [ -z "$BASH" ] && exec $SHELL --login $0 "$@"
    shopt -q login_shell || exec $SHELL --login $0 "$@"
    set +o posix
    ;;
  */zsh)
    [ -z "$ZSH_NAME" ] && exec $SHELL --login $0 "$@"
    [[ -o login ]] || exec $SHELL --login $0 "$@"
    emulate -R sh
    ;;
  */fish)
    source_profiles
    xsess_tmp=$(mktemp /tmp/xsess-env-XXXXXX)
    $SHELL -c "/bin/sh -c 'export -p' > $xsess_tmp"
    . $xsess_tmp
    rm -f $xsess_tmp
    ;;
  *) # Plain sh, ksh, and anything we do not know.
    source_profiles
    ;;
  esac
}

initialize_shell
~/.config/hypr/helpers/import_env.sh system

wait

log "Hyprland compositor session complete, running session $@"

if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

exec dr --foreground --unit hyprland --slice desktop.slice -- Hyprland
