#!/bin/bash
# This time blocklet will use Xresources date format if defined
# or try to determine most appropriate format based on locale and GNOME settings.

DATE_FORMAT=''

if [ -z "$DATE_FORMAT" ]; then # No custom format defined, use system defaults
    DATE_SPEC="%a %b %d"

    TIME_FORMAT=$(gsettings get org.gnome.desktop.interface clock-format)

    if [ "$TIME_FORMAT" == "'12h'" ]; then
        TIME_SPEC="%I:%M"
    else
        TIME_SPEC="%H:%M"
    fi

    DATE_VALUE=$(date "+ $DATE_SPEC, $TIME_SPEC")
else
    DATE_VALUE=$(date "$DATE_FORMAT")
fi


LABEL_ICON=${icon:-}
LABEL_COLOR=${label_color:-"#7B8394"}
VALUE_COLOR=${color:-"#D8DEE9"}
VALUE_FONT=${font:-"Source Code Pro Medium 11"}
echo "<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$DATE_VALUE </span>"

if [ ! -z "$button" ]; then
    /usr/bin/i3-msg -q exec /usr/bin/gnome-control-center datetime
fi
