# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """${custom.docker}$directory$git_branch$git_status$git_state$fill$all$kubernetes$line_break$character"""
palette = "dracula"

[directory]
read_only = " 󰌾"
truncate_to_repo = false

[directory.substitutions]
"~/Code/aina/pro" = "Work"
"~/Code/aina/public" = "Public-work"
"~/Code/lab" = "Lab"
"~/Code/github" = " GH"
"~/Downloads" = ""

[fill]
symbol = " "

[character]
success_symbol = "[󰘍](bold green)"
error_symbol = "[󰘍](bold red)"
vicmd_symbol = "[󰘌](bold yellow)"
vimcmd_replace_one_symbol = "[󰘌](bold purple)"
vimcmd_replace_symbol = "[󰘌](bold purple)"
vimcmd_visual_symbol = "[󰘌](bold yellow)"

[kubernetes]
disabled = false
style = 'blue'
format = '[$symbol $context( \($namespace\))]($style)'

[git_branch]
symbol = " "
style = "bright_green"

[git_status]
style = "bold green"
ahead = '[⇡${count}](green) '
behind = '[⇣${count}](green) '
stashed = '[*${count}](orange) '
modified = '[!${count}](yellow) '
deleted = '[-${count}](red) '
untracked = '[?${count}](cyan) '
staged = '[+${count}](green) '
diverged = '[⇣${behind_count}⇡${ahead_count}](green) '

format = '[$stashed$ahead_behind$modified$deleted$untracked$staged]($style)'

[golang]
symbol = " "

[ruby]
symbol = " "

[nodejs]
symbol = " "

[time]
disabled = false

[custom.docker]
symbol = "󰡨"
style = "bold bright_blue"
files = ["Dockerfile", "docker-compose.yml", "docker-compose.yaml"]
format = '[$symbol($output )]($style) '

[palettes.dracula]
bg = "#282A36"
fg = "#F8F8F2"
selection = "#44475A"
comment = "#6272A4"
red = "#FF5555"
orange = "#FFB86C"
yellow = "#F1FA8C"
green = "#50fa7b"
purple = "#BD93F9"
cyan = "#8BE9FD"
pink = "#FF79C6"
bright_red = "#FF6E6E"
bright_green = "#69FF94"
bright_yellow = "#FFFFA5"
bright_blue = "#D6ACFF"
bright_magenta = "#FF92DF"
bright_cyan = "#A4FFFF"
bright_white = "#FFFFFF"
menu = "#21222C"
visual = "#3E4452"
gutter_fg = "#4B5263"
nontext = "#3B4048"
white = "#ABB2BF"
black = "#191A21"
